//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManagerRESTServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplication
    {
        public tblApplication()
        {
            this.tblApplicationAccessRelationships = new HashSet<tblApplicationAccessRelationship>();
            this.tblApplicationSupports = new HashSet<tblApplicationSupport>();
            this.tblMemberAccesses = new HashSet<tblMemberAccess>();
            this.tblPagers = new HashSet<tblPager>();
        }
    
        public int ApplicationId { get; set; }
        public string ApplicationName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<tblApplicationAccessRelationship> tblApplicationAccessRelationships { get; set; }
        public virtual ICollection<tblApplicationSupport> tblApplicationSupports { get; set; }
        public virtual ICollection<tblMemberAccess> tblMemberAccesses { get; set; }
        public virtual ICollection<tblPager> tblPagers { get; set; }
    }
}
