//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManagerRESTServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccessDetail
    {
        public tblAccessDetail()
        {
            this.tblApplicationAccessRelationships = new HashSet<tblApplicationAccessRelationship>();
            this.tblMemberAccesses = new HashSet<tblMemberAccess>();
        }
    
        public int AccessId { get; set; }
        public string AccessName { get; set; }
        public string Description { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual ICollection<tblApplicationAccessRelationship> tblApplicationAccessRelationships { get; set; }
        public virtual ICollection<tblMemberAccess> tblMemberAccesses { get; set; }
    }
}
