//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManagerRESTServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectCode
    {
        public tblProjectCode()
        {
            this.tblProjectCodeForMembers = new HashSet<tblProjectCodeForMember>();
        }
    
        public int ProjectCodeID { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectDescription { get; set; }
        public string TrackingParameterName { get; set; }
        public Nullable<decimal> TotalFunds { get; set; }
        public Nullable<decimal> UsedFunds { get; set; }
        public Nullable<decimal> RemainingFunds { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> PerMonthLimit { get; set; }
        public Nullable<bool> CanCrossMonthLimit { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<bool> IsDefaultCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual ICollection<tblProjectCodeForMember> tblProjectCodeForMembers { get; set; }
    }
}
