//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManagerRESTServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegionsHoliday
    {
        public int RegionHoildayRelationshipId { get; set; }
        public int HolidayId { get; set; }
        public int RegionId { get; set; }
    
        public virtual tblHoliday tblHoliday { get; set; }
        public virtual tblRegion tblRegion { get; set; }
    }
}
