//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManagerRESTServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegion
    {
        public tblRegion()
        {
            this.tblRegionsHolidays = new HashSet<tblRegionsHoliday>();
        }
    
        public int RegionId { get; set; }
        public string RegionName { get; set; }
    
        public virtual ICollection<tblRegionsHoliday> tblRegionsHolidays { get; set; }
    }
}
