//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManagerRESTServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamManager_NMOEntities : DbContext
    {
        public TeamManager_NMOEntities()
            : base("name=TeamManager_NMOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAccessDetail> tblAccessDetails { get; set; }
        public virtual DbSet<tblApplication> tblApplications { get; set; }
        public virtual DbSet<tblApplicationAccessRelationship> tblApplicationAccessRelationships { get; set; }
        public virtual DbSet<tblApplicationSupport> tblApplicationSupports { get; set; }
        public virtual DbSet<tblBillingRateInfo> tblBillingRateInfoes { get; set; }
        public virtual DbSet<tblHoliday> tblHolidays { get; set; }
        public virtual DbSet<tblLeaveType> tblLeaveTypes { get; set; }
        public virtual DbSet<tblMemberAccess> tblMemberAccesses { get; set; }
        public virtual DbSet<tblMemberdetail> tblMemberdetails { get; set; }
        public virtual DbSet<tblMemberLeaveDetail> tblMemberLeaveDetails { get; set; }
        public virtual DbSet<tblPager> tblPagers { get; set; }
        public virtual DbSet<tblProjectCodeForMember> tblProjectCodeForMembers { get; set; }
        public virtual DbSet<tblProjectCode> tblProjectCodes { get; set; }
        public virtual DbSet<tblRegion> tblRegions { get; set; }
        public virtual DbSet<tblRegionsHoliday> tblRegionsHolidays { get; set; }
        public virtual DbSet<tblTimeSheetBooking> tblTimeSheetBookings { get; set; }
        public virtual DbSet<tblTimeSheetStatu> tblTimeSheetStatus { get; set; }
        public virtual DbSet<tblPagerPlan> tblPagerPlans { get; set; }
    }
}
